#!/usr/bin/env python

from flask.ext.script import Manager, Server

from neu import create_app

manager = Manager(create_app)
manager.add_command('runserver', Server(host='0.0.0.0', port=5006))


if __name__ == "__main__":
    manager.run()
