"""Add rfi model

Revision ID: 5da63e4170a
Revises: 307ef18c7364
Create Date: 2013-09-18 11:01:09.723769
"""

# Revision identifiers, used by Alembic.
revision = '5da63e4170a'
down_revision = '307ef18c7364'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rfi',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=16), nullable=False),
    sa.Column('fname', sa.Unicode(length=256), nullable=False),
    sa.Column('lname', sa.Unicode(length=256), nullable=False),
    sa.Column('email', sa.Unicode(length=256), nullable=False),
    sa.Column('phone', sa.Unicode(length=256), nullable=True),
    sa.Column('zipcode', sa.String(length=16), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('subscribed', sa.Boolean(), nullable=False),
    sa.Column('maker_faire', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_charset='utf8',
    mysql_engine='InnoDB'
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('rfi')
    ### end Alembic commands ###
